pipeline:
  name: olitest_pl_001
  identifier: olitest_pl_001
  projectIdentifier: olitest
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Test Stage
        identifier: Test_Stage
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: |-
                          echo "YNWA"
                          echo "branch: <+trigger.sourceBranch>"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
  variables:
    - name: java_version
      type: String
      description: ""
      required: false
      value: <+input>
    - name: Notes
      type: String
      description: ""
      required: false
      value: <+input>
    - name: branch
      type: String
      description: ""
      required: false
      value: <+input>
