pipeline:
  name: Test CI
  identifier: Test_CI
  projectIdentifier: olitest
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: oligithub
        repoName: testRepo
        build: <+input>
  stages:
    - stage:
        name: Test CI
        identifier: Test_CI
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: echo "test"
